use_frameworks!

platform :ios, '8.0'

target 'HCLGeneralUI_Example' do
  pod 'HCLGeneralUI', :path => '../'

  target 'HCLGeneralUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
